on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job that sends hello to teams
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          msg-to-teams: 'Hello from GitHub!'
        env:
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }} # required
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
