on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job that sends hello to teams
    steps:
      - name: Hello world action step
        uses: madkoo/demo-js-action@v1 # Uses an action in the root directory
        env:
         TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }} # required
        id: hello
        with:
          msg-to-teams: 'Hello from GitHub'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
       
